"""PDF/X-3 conformance for print-ready exports (roadmap 1.20).

Print shops ask for a **PDF/X** — a locked-down PDF whose colours are committed
to a named print condition (an embedded CMYK *output intent* ICC profile), so what
the press lays down matches what was approved. This module turns the RGB
print-production PDF (bleed + crop marks, made by
``graphic_renderer.print_export``) into a PDF/X-3 via Ghostscript.

True to the honest-error rule, it **never fakes conformance**. A real PDF/X-3
needs two things present on the server: a Ghostscript binary *and* a CMYK ICC
profile to embed as the output intent. If either is missing it raises
:class:`PdfXUnavailable` — the caller still has the ordinary CMYK or RGB
print-ready PDF, which every digital print shop accepts and RIPs itself.

The Ghostscript argument string and the ``PDFX_def.ps`` definition are built by
pure functions (:func:`pdfx_definition_ps`, :func:`ghostscript_pdfx_args`) so they
are fully unit-testable without Ghostscript installed — the same pattern the
1.19 transcode engine uses for its FFmpeg arg builders.
"""

from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path
from typing import Optional

# PDF/X flavours we support → the GTS_PDFXVersion string Ghostscript expects.
PDFX_STANDARDS: dict[str, str] = {
    "PDF/X-3": "PDF/X-3:2002",
    "PDF/X-1a": "PDF/X-1a:2003",
}
_DEFAULT_STANDARD = "PDF/X-3"

# Candidate CMYK output-intent profiles, in resolution order. The operator can
# point at any profile via the env var; otherwise we look for the common
# system / Ghostscript-bundled CMYK profiles. We bundle none ourselves (no
# binary blobs of uncertain licence in the repo).
_ENV_PROFILE = "MEDIAHUB_PRINT_ICC_PROFILE"
_CANDIDATE_PROFILES: tuple[str, ...] = (
    "/usr/share/color/icc/ghostscript/default_cmyk.icc",
    "/usr/share/ghostscript/iccprofiles/default_cmyk.icc",
    "/usr/share/color/icc/CGATS001Compat-v2-micro.icc",
    "/usr/share/color/icc/colord/CoatedFOGRA39.icc",
)


class PdfXUnavailable(RuntimeError):
    """PDF/X export was requested but the toolchain (Ghostscript + ICC) is absent.

    Honest by design: the caller keeps the ordinary print-ready PDF (RGB or
    DeviceCMYK with bleed + crop marks), which print shops accept and convert
    with their own profiled RIP.
    """


def _gs_binary() -> Optional[str]:
    for name in ("gs", "gswin64c", "gswin32c"):
        path = shutil.which(name)
        if path:
            return path
    return None


def ghostscript_available() -> bool:
    """True if a Ghostscript binary is on PATH."""
    return _gs_binary() is not None


def resolve_icc_profile(explicit: Optional[str] = None) -> Optional[str]:
    """Find a CMYK output-intent ICC profile, or ``None`` if there isn't one.

    Resolution order: an ``explicit`` path → the ``MEDIAHUB_PRINT_ICC_PROFILE``
    env var → a short list of common system / Ghostscript CMYK profiles.
    """
    for candidate in (explicit, os.environ.get(_ENV_PROFILE), *_CANDIDATE_PROFILES):
        if candidate and Path(candidate).is_file():
            return str(candidate)
    return None


def pdfx_available(icc_profile: Optional[str] = None) -> bool:
    """True only when a real PDF/X-3 can be produced (Ghostscript + an ICC)."""
    return ghostscript_available() and resolve_icc_profile(icc_profile) is not None


def _ps_str(value: str) -> str:
    """Escape a Python string for a PostScript literal ``(...)``."""
    return value.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")


def pdfx_definition_ps(
    *,
    icc_profile_path: str,
    title: str = "MediaHub print export",
    condition: str = "Coated FOGRA39 (ISO 12647-2:2004)",
    condition_id: str = "FOGRA39",
    standard: str = _DEFAULT_STANDARD,
) -> str:
    """Build the ``PDFX_def.ps`` that declares the output intent (pure, testable).

    This is the canonical Ghostscript PDF/X definition: it embeds the CMYK
    profile as a stream and references it from a ``/GTS_PDFX`` OutputIntent on
    the document catalog, with the document's ``GTS_PDFXVersion`` set to the
    requested flavour.
    """
    version = PDFX_STANDARDS.get(standard, PDFX_STANDARDS[_DEFAULT_STANDARD])
    icc = _ps_str(str(icc_profile_path))
    return "\n".join(
        [
            "%!",
            "% PDF/X-3 definition generated by MediaHub print_ready.pdfx",
            f"[ /GTS_PDFXVersion ({version})",
            f"  /Title ({_ps_str(title)})",
            "  /Trapped /False",
            "  /DOCINFO pdfmark",
            "",
            "[ /_objdef {icc_PDFX} /type /stream /OBJ pdfmark",
            "[ {icc_PDFX} << /N 4 >> /PUT pdfmark",
            f"[ {{icc_PDFX}} ({icc}) (r) file /PUT pdfmark",
            "[ /_objdef {OutputIntent_PDFX} /type /dict /OBJ pdfmark",
            "[ {OutputIntent_PDFX} <<",
            "    /Type /OutputIntent",
            "    /S /GTS_PDFX",
            f"    /OutputCondition ({_ps_str(condition)})",
            f"    /OutputConditionIdentifier ({_ps_str(condition_id)})",
            "    /DestOutputProfile {icc_PDFX}",
            f"    /Info ({_ps_str(condition)})",
            "  >> /PUT pdfmark",
            "[ {Catalog} << /OutputIntents [ {OutputIntent_PDFX} ] >> /PUT pdfmark",
            "",
        ]
    )


def ghostscript_pdfx_args(
    gs: str,
    *,
    src_pdf: Path,
    def_ps: Path,
    out_pdf: Path,
    icc_profile: str,
) -> list[str]:
    """The Ghostscript argv that converts ``src_pdf`` → a PDF/X CMYK PDF (pure)."""
    return [
        gs,
        "-dPDFX",
        "-dBATCH",
        "-dNOPAUSE",
        "-dNOOUTERSAVE",
        "-dSAFER",
        "-sDEVICE=pdfwrite",
        "-dProcessColorModel=/DeviceCMYK",
        "-sColorConversionStrategy=CMYK",
        f"-sOutputICCProfile={icc_profile}",
        "-dPDFSETTINGS=/printer",
        f"-sOutputFile={out_pdf}",
        str(def_ps),
        str(src_pdf),
    ]


def export_pdfx(
    src_pdf: Path,
    out_pdf: Optional[Path] = None,
    *,
    standard: str = _DEFAULT_STANDARD,
    icc_profile: Optional[str] = None,
    title: str = "MediaHub print export",
) -> Path:
    """Convert an RGB print PDF to a PDF/X-3 (CMYK output intent) via Ghostscript.

    Raises :class:`PdfXUnavailable` when Ghostscript or a CMYK ICC profile is not
    present — never a fake-tagged file. Returns the PDF/X path.
    """
    src_pdf = Path(src_pdf)
    if not src_pdf.exists():
        raise FileNotFoundError(src_pdf)
    gs = _gs_binary()
    profile = resolve_icc_profile(icc_profile)
    if gs is None or profile is None:
        missing = "Ghostscript" if gs is None else "a CMYK ICC output-intent profile"
        raise PdfXUnavailable(
            f"PDF/X export needs {missing}, which isn't available. The print-ready "
            f"PDF (bleed + crop marks) is still valid for a print shop."
        )
    final = Path(out_pdf) if out_pdf else src_pdf
    final.parent.mkdir(parents=True, exist_ok=True)
    def_ps = final.with_suffix(final.suffix + ".pdfx_def.ps")
    def_ps.write_text(
        pdfx_definition_ps(icc_profile_path=profile, title=title, standard=standard),
        encoding="utf-8",
    )
    tmp = final.with_suffix(final.suffix + ".pdfx.tmp.pdf")
    args = ghostscript_pdfx_args(
        gs, src_pdf=src_pdf, def_ps=def_ps, out_pdf=tmp, icc_profile=profile
    )
    try:
        subprocess.run(args, check=True, capture_output=True, timeout=180)
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired) as e:  # pragma: no cover
        for p in (tmp, def_ps):
            try:
                p.unlink()
            except OSError:
                pass
        raise PdfXUnavailable(f"Ghostscript PDF/X conversion failed: {e}") from e
    tmp.replace(final)
    try:
        def_ps.unlink()
    except OSError:  # pragma: no cover
        pass
    return final


__all__ = [
    "PDFX_STANDARDS",
    "PdfXUnavailable",
    "ghostscript_available",
    "resolve_icc_profile",
    "pdfx_available",
    "pdfx_definition_ps",
    "ghostscript_pdfx_args",
    "export_pdfx",
]
