"""
Stub pack store — persists content cards generated by the four AI stubs
(Free Text / Event Preview / Sponsor Post / Session Update) so they survive
refresh and can be listed, revisited and exported.

Files are written under ``DATA_DIR/stub_packs/<pack_id>.json``.

Each pack has:
  pack_id:    short hex id, also the filename stem
  created_at: ISO-8601 UTC timestamp
  stub_type:  free_text | weekend_preview | sponsor_post | session_update
  title:      human-friendly title (taken from form input where possible)
  form_data:  the raw form values that produced the cards
  cards:      list of {platform, caption, hashtags, confidence, notes}
"""
from __future__ import annotations

import json
import os
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional


def _data_dir() -> Path:
    """Resolve DATA_DIR the same way web.py does — env var first, repo default."""
    env = os.environ.get("DATA_DIR")
    if env:
        return Path(env)
    # Fallback: repo-root/data, computed relative to this file.
    return Path(__file__).resolve().parents[3] / "data"


def _packs_dir() -> Path:
    d = _data_dir() / "stub_packs"
    d.mkdir(parents=True, exist_ok=True)
    return d


def _derive_title(stub_type: str, form_data: dict) -> str:
    """Pick the most informative title from form input."""
    if stub_type == "free_text":
        txt = (form_data.get("free_text") or "").strip()
        if not txt:
            return "Free text draft"
        # First non-empty line, capped at 80 chars
        first = next((l.strip() for l in txt.splitlines() if l.strip()), "")
        return (first[:77] + "…") if len(first) > 80 else (first or "Free text draft")
    meet = (form_data.get("meet_name") or "").strip()
    if stub_type == "weekend_preview":
        return f"Preview — {meet}" if meet else "Event preview"
    if stub_type == "sponsor_post":
        sponsor = (form_data.get("sponsor_name") or "").strip()
        if sponsor and meet:
            return f"{sponsor} × {meet}"
        return f"Sponsor post — {sponsor or meet or 'draft'}"
    if stub_type == "session_update":
        return f"Live — {meet}" if meet else "Session update"
    return "Content draft"


def save_pack(stub_type: str, form_data: dict, cards: list[dict]) -> dict:
    """Persist a generated pack to disk; return the saved record (with pack_id)."""
    pack_id = uuid.uuid4().hex[:10]
    record = {
        "pack_id":    pack_id,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "stub_type":  stub_type,
        "title":      _derive_title(stub_type, form_data),
        "form_data":  {k: v for k, v in (form_data or {}).items() if isinstance(v, (str, int, float))},
        "cards":      list(cards or []),
    }
    path = _packs_dir() / f"{pack_id}.json"
    path.write_text(json.dumps(record, indent=2, ensure_ascii=False), encoding="utf-8")
    return record


def load_pack(pack_id: str) -> Optional[dict]:
    """Load a single pack record, or None if missing/invalid."""
    if not pack_id or not pack_id.replace("-", "").isalnum():
        return None
    path = _packs_dir() / f"{pack_id}.json"
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


def list_packs(limit: int = 50) -> list[dict]:
    """List the most recent packs, newest first."""
    items: list[dict] = []
    for p in _packs_dir().glob("*.json"):
        try:
            data = json.loads(p.read_text(encoding="utf-8"))
            items.append({
                "pack_id":    data.get("pack_id", p.stem),
                "created_at": data.get("created_at", ""),
                "stub_type":  data.get("stub_type", "other"),
                "title":      data.get("title", "Untitled"),
                "n_cards":    len(data.get("cards") or []),
            })
        except (OSError, json.JSONDecodeError):
            continue
    items.sort(key=lambda r: r.get("created_at", ""), reverse=True)
    return items[:limit]


def delete_pack(pack_id: str) -> bool:
    if not pack_id or not pack_id.replace("-", "").isalnum():
        return False
    path = _packs_dir() / f"{pack_id}.json"
    if not path.exists():
        return False
    try:
        path.unlink()
        return True
    except OSError:
        return False


def export_pack_text(record: dict) -> str:
    """Build a plain-text export of a pack — one section per card."""
    if not record:
        return ""
    lines: list[str] = []
    lines.append(record.get("title", "Content pack"))
    lines.append("=" * 60)
    lines.append(f"Generated: {record.get('created_at', '')}")
    lines.append(f"Type: {record.get('stub_type', '')}")
    lines.append("")
    for i, card in enumerate(record.get("cards") or [], start=1):
        platform = card.get("platform", "Post")
        caption = (card.get("caption") or "").strip()
        hashtags = card.get("hashtags") or []
        try:
            conf = int(round(float(card.get("confidence", 0.6)) * 100))
        except (TypeError, ValueError):
            conf = 60
        lines.append(f"--- Card {i} · {platform} · {conf}% confidence ---")
        lines.append(caption)
        if hashtags:
            lines.append("")
            lines.append(" ".join(f"#{str(h).lstrip('#')}" for h in hashtags))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"
