"""
Stub pack store — persists content cards generated by the four AI stubs
(Free Text / Event Preview / Sponsor Post / Session Update) so they survive
refresh and can be listed, revisited and exported.

Files are written under ``DATA_DIR/stub_packs/<pack_id>.json``.

Each pack has:
  pack_id:    short hex id, also the filename stem
  profile_id: organisation that owns the pack (None for legacy/anonymous)
  created_at: ISO-8601 UTC timestamp
  stub_type:  free_text | event_preview | sponsor_activation | session_update
              (canonical post-type slugs, ADR-0013; packs persisted before the
              rename carry "weekend_preview"/"sponsor_post" and are normalised
              on load via post_types.canonical_slug)
  title:      human-friendly title (taken from form input where possible)
  form_data:  the raw form values that produced the cards
  cards:      list of {platform, caption, hashtags, confidence, notes}
"""

from __future__ import annotations

import json
import os
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional


def _data_dir() -> Path:
    """Resolve DATA_DIR the same way web.py does — env var first, repo default."""
    env = os.environ.get("DATA_DIR")
    if env:
        return Path(env)
    # Fallback: repo-root/data, computed relative to this file.
    return Path(__file__).resolve().parents[3] / "data"


def _packs_dir() -> Path:
    d = _data_dir() / "stub_packs"
    d.mkdir(parents=True, exist_ok=True)
    return d


def _derive_title(stub_type: str, form_data: dict) -> str:
    """Pick the most informative title from form input."""
    if stub_type == "free_text":
        txt = (form_data.get("free_text") or "").strip()
        if not txt:
            return "Free text draft"
        # First non-empty line, capped at 80 chars
        first = next((l.strip() for l in txt.splitlines() if l.strip()), "")
        return (first[:77] + "…") if len(first) > 80 else (first or "Free text draft")
    meet = (form_data.get("meet_name") or "").strip()
    if stub_type == "event_preview":
        return f"Preview — {meet}" if meet else "Event preview"
    if stub_type == "sponsor_activation":
        sponsor = (form_data.get("sponsor_name") or "").strip()
        if sponsor and meet:
            return f"{sponsor} × {meet}"
        return f"Sponsor post — {sponsor or meet or 'draft'}"
    if stub_type == "session_update":
        return f"Live — {meet}" if meet else "Session update"
    return "Content draft"


def save_pack(
    stub_type: str, form_data: dict, cards: list[dict], profile_id: Optional[str] = None
) -> dict:
    """Persist a generated pack to disk; return the saved record (with pack_id).

    ``profile_id`` is the organisation that owns the pack; it's used by
    the draft routes to enforce tenant isolation. Pre-existing packs on
    disk that have no ``profile_id`` stamped are still readable (lenient
    legacy fallback), but every pack saved going forward names its owner.
    """
    from mediahub.club_platform.post_types import canonical_slug

    stub_type = canonical_slug(stub_type)
    pack_id = uuid.uuid4().hex[:10]
    record = {
        "pack_id": pack_id,
        "profile_id": (profile_id or "").strip() or None,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "stub_type": stub_type,
        "title": _derive_title(stub_type, form_data),
        "form_data": {
            k: v for k, v in (form_data or {}).items() if isinstance(v, (str, int, float))
        },
        "cards": list(cards or []),
    }
    path = _packs_dir() / f"{pack_id}.json"
    path.write_text(json.dumps(record, indent=2, ensure_ascii=False), encoding="utf-8")
    return record


def update_pack(
    pack_id: str,
    *,
    cards: Optional[list[dict]] = None,
    form_data_updates: Optional[dict] = None,
) -> Optional[dict]:
    """Update an existing pack in place (cards and/or form_data keys).

    Returns the updated record, or None when the pack doesn't exist.
    Used by tools that refine a saved draft after the fact — e.g. the
    athlete-spotlight tone rewrite, which swaps the caption without
    minting a new pack id.
    """
    rec = load_pack(pack_id)
    if rec is None:
        return None
    if cards is not None:
        rec["cards"] = list(cards)
    if form_data_updates:
        fd = dict(rec.get("form_data") or {})
        fd.update({k: v for k, v in form_data_updates.items() if isinstance(v, (str, int, float))})
        rec["form_data"] = fd
    path = _packs_dir() / f"{pack_id}.json"
    path.write_text(json.dumps(rec, indent=2, ensure_ascii=False), encoding="utf-8")
    return rec


def load_pack(pack_id: str) -> Optional[dict]:
    """Load a single pack record, or None if missing/invalid."""
    if not pack_id or not pack_id.replace("-", "").isalnum():
        return None
    path = _packs_dir() / f"{pack_id}.json"
    if not path.exists():
        return None
    try:
        rec = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    if isinstance(rec, dict) and rec.get("stub_type"):
        # Packs saved before ADR-0013 carry legacy type strings; normalise so
        # every downstream branch sees the canonical slug.
        from mediahub.club_platform.post_types import canonical_slug

        rec["stub_type"] = canonical_slug(rec["stub_type"])
    return rec


def list_packs(limit: int = 50) -> list[dict]:
    """List the most recent packs, newest first."""
    from mediahub.club_platform.post_types import canonical_slug

    items: list[dict] = []
    for p in _packs_dir().glob("*.json"):
        try:
            data = json.loads(p.read_text(encoding="utf-8"))
            items.append(
                {
                    "pack_id": data.get("pack_id", p.stem),
                    "created_at": data.get("created_at", ""),
                    "stub_type": canonical_slug(data.get("stub_type", "other")),
                    "title": data.get("title", "Untitled"),
                    "n_cards": len(data.get("cards") or []),
                }
            )
        except (OSError, json.JSONDecodeError):
            continue
    items.sort(key=lambda r: r.get("created_at", ""), reverse=True)
    return items[:limit]


_VALID_STATUSES: frozenset[str] = frozenset({"queue", "approved", "rejected"})


def update_card_status(pack_id: str, card_idx: int, status: str) -> Optional[dict]:
    """Set the approval `status` on a single card within a saved pack.

    Returns the updated record on success, or None if the pack/card/status
    is invalid. Approval drives the per-card pill on the stub render pages
    and is read by the export step downstream.
    """
    if status not in _VALID_STATUSES:
        return None
    rec = load_pack(pack_id)
    if not rec:
        return None
    cards = rec.get("cards") or []
    if not isinstance(card_idx, int) or card_idx < 0 or card_idx >= len(cards):
        return None
    card = cards[card_idx]
    if not isinstance(card, dict):
        return None
    card["status"] = status
    rec["cards"] = cards
    path = _packs_dir() / f"{pack_id}.json"
    path.write_text(json.dumps(rec, indent=2, ensure_ascii=False), encoding="utf-8")
    return rec


def replace_cards(pack_id: str, new_cards: list[dict]) -> Optional[dict]:
    """Swap a pack's cards for a freshly-regenerated set.

    The prior cards are archived into a capped ``card_history`` list so the
    next regenerate can feed them to the content engine as an avoid-set —
    that's what keeps every regenerate genuinely different. Returns the
    updated record, or None if the pack is missing.
    """
    rec = load_pack(pack_id)
    if not rec:
        return None
    prior = rec.get("cards") or []
    history = list(rec.get("card_history") or [])
    for c in prior:
        if isinstance(c, dict) and (c.get("caption") or "").strip():
            history.append(
                {
                    "platform": c.get("platform", ""),
                    "caption": c.get("caption", ""),
                }
            )
    rec["card_history"] = history[-24:]
    rec["cards"] = list(new_cards or [])
    path = _packs_dir() / f"{pack_id}.json"
    path.write_text(json.dumps(rec, indent=2, ensure_ascii=False), encoding="utf-8")
    return rec


def delete_pack(pack_id: str) -> bool:
    if not pack_id or not pack_id.replace("-", "").isalnum():
        return False
    path = _packs_dir() / f"{pack_id}.json"
    if not path.exists():
        return False
    try:
        path.unlink()
        return True
    except OSError:
        return False


def export_pack_text(record: dict) -> str:
    """Build a plain-text export of a pack — one section per card."""
    if not record:
        return ""
    lines: list[str] = []
    lines.append(record.get("title", "Content pack"))
    lines.append("=" * 60)
    lines.append(f"Generated: {record.get('created_at', '')}")
    lines.append(f"Type: {record.get('stub_type', '')}")
    lines.append("")
    for i, card in enumerate(record.get("cards") or [], start=1):
        platform = card.get("platform", "Post")
        caption = (card.get("caption") or "").strip()
        hashtags = card.get("hashtags") or []
        try:
            conf = int(round(float(card.get("confidence", 0.6)) * 100))
        except (TypeError, ValueError):
            conf = 60
        lines.append(f"--- Card {i} · {platform} · {conf}% confidence ---")
        lines.append(caption)
        if hashtags:
            lines.append("")
            lines.append(" ".join(f"#{str(h).lstrip('#')}" for h in hashtags))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"
