#!/usr/bin/env python3
"""
build_inventories.py — Phase F of the V9 handoff.

Walks the export and writes auto-generated inventories under docs/.
"""

from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path

# Repo root, derived from this script's location (scripts/build_inventories.py).
# Previously hard-coded to the one-off V9 export path, which left every
# inventory un-regenerable (and therefore stale) outside that machine.
ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"

# Make mediahub importable.
sys.path.insert(0, str(ROOT / "src"))


# ---------- INVENTORY.md ----------
def _repo_files() -> list[Path]:
    """Repo files only (tracked + untracked-but-not-ignored).

    A raw rglob walk also swept in machine-local runtime state — egg-info from
    the editable install, caches, gitignored DBs — so the committed inventory
    depended on whose machine regenerated it.
    """
    try:
        raw = subprocess.run(
            ["git", "ls-files", "-z", "--cached", "--others", "--exclude-standard"],
            cwd=ROOT,
            capture_output=True,
            check=True,
        ).stdout
        return [ROOT / f for f in raw.decode().split("\0") if f]
    except Exception:
        return [p for p in ROOT.rglob("*") if p.is_file()]


def write_inventory():
    out = [
        "# Inventory\n\n",
        "Every file in the repo, with size and a one-line purpose.\n\n",
        "_Auto-generated by `scripts/build_inventories.py`._\n\n",
        "| Path | Size (bytes) | Purpose |\n",
        "|------|---:|---|\n",
    ]
    skip = {".git", "__pycache__", ".pytest_cache", "node_modules"}
    for p in sorted(_repo_files()):
        if any(part in skip for part in p.parts):
            continue
        if not p.is_file():
            continue
        rel = p.relative_to(ROOT)
        if str(rel).startswith("docs/build_reports/"):
            purpose = "Build log / evidence report"
        elif str(rel).startswith("legacy/"):
            purpose = "Legacy package preserved verbatim"
        elif str(rel).startswith("samples/"):
            purpose = "Representative meet sample"
        elif str(rel).startswith("data/ontology/"):
            purpose = "Canonical lookup table"
        elif str(rel).startswith("data/voices/"):
            purpose = "Voice profile"
        elif str(rel).startswith("data/discovered/"):
            purpose = "Runtime discovery cache (.gitkeep)"
        elif str(rel).startswith("tests/"):
            purpose = "Test suite"
        elif str(rel).startswith("src/mediahub/"):
            purpose = _purpose_from_module(rel)
        elif rel.suffix == ".md":
            purpose = "Documentation"
        else:
            purpose = ""
        out.append(f"| `{rel}` | {p.stat().st_size} | {purpose} |\n")
    (DOCS / "INVENTORY.md").write_text("".join(out))
    print(f"INVENTORY.md: {len(out) - 5} files listed")


def _purpose_from_module(rel: Path) -> str:
    parts = rel.parts
    # src/mediahub/<pkg>/...
    if len(parts) >= 3:
        pkg = parts[2]
        m = {
            "web": "Flask UI / helpers",
            "pipeline": "Upload→cards orchestrator",
            "interpreter": "Format-agnostic ingest",
            "recognition": "Sport-agnostic detector bus",
            "recognition_swim": "Swim achievement detectors",
            "pb_discovery": "PB lookup engine",
            "context_engine": "Identity + ontology + trust",
            "voice": "Caption voice profiles",
            "brand": "Brand kit logic",
            "workflow": "Card status persistence",
            "club_platform": "Content type registry",
            "graphic_renderer": "HTML→PNG renderer",
            "creative_brief": "LLM creative direction",
            "media_ai": "LLM + cutout providers",
            "media_library": "Asset store",
            "media_requirements": "Content-type → media rules",
            "venue_search": "Pool venue image search",
            "inspiration": "Pattern + exemplar library",
            "content_pack": "Pack ZIP builder",
            "content_pack_visual": "Visual pack integration",
            "web_research": "Web research client",
        }
        return m.get(pkg, "MediaHub source module")
    return "MediaHub source"


# ---------- ROUTE_INVENTORY.md ----------
def write_routes():
    """Dump Flask app.url_map programmatically."""
    out = [
        "# Route Inventory\n\n",
        "All Flask routes registered by `mediahub.web.create_app()`.\n\n",
        "_Auto-generated from `app.url_map` by `scripts/build_inventories.py`._\n\n",
        "| Endpoint | Methods | Rule |\n",
        "|---|---|---|\n",
    ]
    try:
        from mediahub.web.web import create_app

        app = create_app()
        for r in sorted(app.url_map.iter_rules(), key=lambda x: str(x)):
            methods = ",".join(
                sorted(m for m in (r.methods or set()) if m not in {"HEAD", "OPTIONS"})
            )
            out.append(f"| `{r.endpoint}` | `{methods}` | `{r.rule}` |\n")
    except Exception as e:
        out.append(f"\n_Error introspecting app: {e}_\n")
    (DOCS / "ROUTE_INVENTORY.md").write_text("".join(out))
    print("ROUTE_INVENTORY.md written")


# ---------- API_INVENTORY.md ----------
def write_api():
    out = [
        "# API Inventory\n\n",
        "Every `/api/*` and key non-API endpoint in `mediahub.web.web`, ",
        "with the request/response shape inferred from the source.\n\n",
        "_Auto-generated by `scripts/build_inventories.py` (Flask url_map filtered ",
        "to `/api/*`)._\n\n",
        "| Endpoint | Methods | Rule | Notes |\n",
        "|---|---|---|---|\n",
    ]
    try:
        from mediahub.web.web import create_app

        app = create_app()
        for r in sorted(app.url_map.iter_rules(), key=lambda x: str(x)):
            if "/api/" in r.rule or r.rule.startswith("/healthz"):
                methods = ",".join(
                    sorted(m for m in (r.methods or set()) if m not in {"HEAD", "OPTIONS"})
                )
                out.append(
                    f"| `{r.endpoint}` | `{methods}` | `{r.rule}` | "
                    f"See source `mediahub.web.web::{r.endpoint}` |\n"
                )
    except Exception as e:
        out.append(f"\n_Error: {e}_\n")
    out.append("\n## Conventions\n\n")
    out.append("- All response bodies are JSON (`application/json`).\n")
    out.append("- All POST request bodies are JSON unless the endpoint takes a multipart upload.\n")
    out.append('- Errors return `{"error": "<message>"}` with the appropriate HTTP status.\n')
    (DOCS / "API_INVENTORY.md").write_text("".join(out))
    print("API_INVENTORY.md written")


# ---------- ENV_INVENTORY.md ----------
def env_inventory_md() -> str:
    """Build the ENV_INVENTORY.md content (pure — no file write).

    Separated from ``write_env`` so a CI test can assert the committed file is
    current (``tests/test_inventories_fresh.py``) — otherwise the inventory
    silently rots whenever an env var is added without regenerating.
    """
    # Match os.environ.get(...), os.getenv(...), environ[...] subscripts, and
    # aliased access (e.g. `import os as _os; _os.environ.get`) by anchoring on
    # `environ`/`getenv` rather than a literal `os.` prefix — the narrow old
    # pattern missed subscript and aliased reads. (Provider keys resolved
    # indirectly, like GEMINI_API_KEY/ANTHROPIC_API_KEY, are recovered by the
    # secrets_store merge below, not by this regex.)
    pat = re.compile(r"(?:environ\.get\(|getenv\(|environ\[)\s*['\"]([A-Z_][A-Z0-9_]*)['\"]")
    found: dict[str, list[str]] = {}
    for p in sorted((ROOT / "src").rglob("*.py")):
        try:
            text = p.read_text()
        except Exception:
            continue
        for m in pat.finditer(text):
            found.setdefault(m.group(1), []).append(str(p.relative_to(ROOT)))

    # Credentials resolved INDIRECTLY (via get_secret()/_resolve_key over a tuple
    # of names) never appear as a literal in an environ.get() call, so the grep
    # above misses them — including GEMINI_API_KEY / ANTHROPIC_API_KEY. Merge the
    # codebase's own source-of-truth mapping so the security-critical keys are
    # never silently absent from the inventory.
    try:
        from mediahub.web.secrets_store import _SECRET_ENV_NAMES

        for names in _SECRET_ENV_NAMES.values():
            for name in names:
                found.setdefault(name, []).append(
                    "src/mediahub/web/secrets_store.py (via get_secret)"
                )
    except Exception as exc:  # never let an import break the inventory
        print(f"  note: could not merge secrets_store mapping: {exc}", file=sys.stderr)
    out = [
        "# Environment Variable Inventory\n\n",
        "Every environment variable read by the live source.\n\n",
        "_Auto-generated by grepping `os.environ.get` / `os.getenv` in `src/`._\n\n",
        "| Var | Used in |\n",
        "|---|---|\n",
    ]
    for k in sorted(found):
        files = sorted(set(found[k]))
        out.append(
            f"| `{k}` | {', '.join(f'`{f}`' for f in files[:6])}"
            f"{' …' if len(files) > 6 else ''} |\n"
        )
    out.append("\nSee `.env.example` for descriptions and defaults.\n")
    # Hand-written security appendix (least-privilege key scoping) — kept in
    # its own file so this generator can fully own the table above while the
    # freshness test still covers the whole committed document.
    extra = DOCS / "_env_inventory_security.md"
    if extra.exists():
        out.append("\n" + extra.read_text())
    return "".join(out)


def write_env():
    content = env_inventory_md()
    (DOCS / "ENV_INVENTORY.md").write_text(content)
    print(f"ENV_INVENTORY.md: {content.count(chr(10) + '| `')} vars")


# ---------- DETECTOR_INVENTORY.md ----------
def write_detectors():
    out = [
        "# Detector Inventory\n\n",
        "Every achievement detector currently live, swim-only.\n\n",
        "_Auto-generated by `scripts/build_inventories.py` ",
        "(walks `recognition_swim/achievements/` + ",
        "`legacy/swim_content_v5/achievements/`)._\n\n",
    ]

    out.append("## V8 detectors (`mediahub.recognition_swim.achievements`)\n\n")
    out.append("| File | Class / function | Trigger |\n|---|---|---|\n")
    live_dir = ROOT / "src" / "mediahub" / "recognition_swim" / "achievements"
    for p in sorted(live_dir.glob("*.py")):
        if p.name == "__init__.py":
            continue
        cls = _first_class(p)
        trigger = _first_docstring_line(p)
        out.append(f"| `{p.name}` | `{cls}` | {trigger} |\n")

    out.append("\n## V5 detectors (`legacy/swim_content_v5/achievements`)\n\n")
    out.append("| File | Class / function | Trigger |\n|---|---|---|\n")
    legacy_dir = ROOT / "legacy" / "swim_content_v5" / "achievements"
    if legacy_dir.exists():
        for p in sorted(legacy_dir.glob("*.py")):
            if p.name == "__init__.py":
                continue
            cls = _first_class(p)
            trigger = _first_docstring_line(p)
            out.append(f"| `{p.name}` | `{cls}` | {trigger} |\n")

    (DOCS / "DETECTOR_INVENTORY.md").write_text("".join(out))
    print("DETECTOR_INVENTORY.md written")


def _first_class(p: Path) -> str:
    text = p.read_text()
    m = re.search(r"^class\s+(\w+)", text, re.MULTILINE)
    return m.group(1) if m else "—"


def _first_docstring_line(p: Path) -> str:
    text = p.read_text()
    m = re.search(r'"""([^\n"]+)', text)
    return m.group(1).strip() if m else ""


# ---------- PROMPT_INVENTORY.md ----------
def write_prompts():
    out = [
        "# Prompt Inventory\n\n",
        "Every Claude / LLM prompt template in the source. ",
        "Search performed across all `*.py` for triple-quoted strings ",
        "containing `system:` or `\\nUser:` markers, plus explicit ",
        "`_SYSTEM_PROMPT`/`SYSTEM`/`PROMPT` variables.\n\n",
    ]
    out.append("| File | Constant | First line of prompt |\n|---|---|---|\n")
    pat = re.compile(
        r"^\s*(_SYSTEM_PROMPT|SYSTEM|PROMPT|_PROMPT|"
        r"USER_PROMPT|VISION_PROMPT|CAPTION_PROMPT)"
        r"\s*[:=]\s*",
        re.MULTILINE,
    )
    for p in (ROOT / "src").rglob("*.py"):
        text = p.read_text()
        for m in pat.finditer(text):
            after = text[m.end() : m.end() + 600]
            # Look for the first triple-quoted string that follows.
            mq = re.search(r'(?:"""|f""")(.*?)(?:"""|""")', after, re.DOTALL)
            if not mq:
                continue
            first_line = mq.group(1).strip().splitlines()[0][:120] if mq.group(1).strip() else ""
            rel = p.relative_to(ROOT)
            out.append(f"| `{rel}` | `{m.group(1)}` | {first_line} |\n")

    out.append("\n## Where to read the full prompts\n\n")
    out.append("- AI caption — `src/mediahub/web/ai_caption.py`\n")
    out.append("- Vision creative direction — `src/mediahub/creative_brief/generator.py`\n")
    out.append("- Media description — `src/mediahub/media_library/describe.py`\n")
    out.append("- Voice render guidance — `src/mediahub/voice/multi_tone_renderer.py`\n")
    (DOCS / "PROMPT_INVENTORY.md").write_text("".join(out))
    print("PROMPT_INVENTORY.md written")


# ---------- SYSTEM_MAP.md ----------
def write_system_map():
    out = [
        "# System Map\n\n",
        "ASCII diagram of how the live packages fit together.\n\n",
        "```\n",
        " ┌────────────────────────────────────────────────────────────────────┐\n",
        " │                       mediahub.web (Flask app)                     │\n",
        " │   /upload → upload_post → spawns thread → run_pipeline_v4          │\n",
        " │   /review/<id> ← reads runs_v4/<id>.json                           │\n",
        " │   /api/runs/<id>/* ← status / cards / trust / export               │\n",
        " └─────────────────────────────────┬──────────────────────────────────┘\n",
        "                                   │\n",
        "                     ┌─────────────▼────────────┐\n",
        "                     │   mediahub.pipeline       │\n",
        "                     │   pipeline_v4 + bridges   │\n",
        "                     └──┬───────┬────────┬───────┘\n",
        "                        │       │        │\n",
        "          ┌─────────────▼─┐ ┌───▼────┐  ┌▼──────────────┐\n",
        "          │ interpreter   │ │ pb_    │  │ recognition_  │\n",
        "          │ (HY3/SDIF/   │  │ disc.  │  │ swim          │\n",
        "          │  PDF/HTML)   │  │ +trust │  │ + V5 legacy   │\n",
        "          └──────┬───────┘ └───┬────┘  └───────┬───────┘\n",
        "                 │             │               │\n",
        "                 └─────┐  ┌────┘     ┌─────────┘\n",
        "                       ▼  ▼          ▼\n",
        "                 ┌──────────────────────────┐\n",
        "                 │  recognition.ranker      │\n",
        "                 │  (sport-agnostic)        │\n",
        "                 └────────────┬─────────────┘\n",
        "                              │\n",
        "             ┌────────────────┼─────────────────┐\n",
        "             ▼                ▼                 ▼\n",
        "       creative_brief  graphic_renderer    web.ai_caption\n",
        "       (LLM)           (HTML/CSS→PNG)        (LLM/fallback)\n",
        "             │                │                 │\n",
        "             └────────────────┴─────────────────┘\n",
        "                              │\n",
        "                              ▼\n",
        "                       content_pack (ZIP)\n",
        "```\n\n",
        "## Sub-system dependencies\n\n",
        "- `voice` ← used by `ai_caption`, `creative_brief`, `humanise`.\n",
        "- `brand` ← used by `creative_brief`, `graphic_renderer`.\n",
        "- `media_library` ← used by `creative_brief`, `graphic_renderer`.\n",
        "- `media_requirements` ← used by `pipeline_v4` to validate readiness.\n",
        "- `venue_search` + `web_research` ← used by `creative_brief` for hero photos.\n",
        "- `context_engine` ← used by `pipeline_v4` (identity), `pb_discovery` (trust).\n",
        "- `inspiration` ← used by `creative_brief` for angle selection.\n",
        "- `history` ← used by V5 detectors for past-result lookups.\n",
        "- `workflow` ← used by `web.web` to persist card states.\n",
        "- `club_platform` ← used by `pipeline_v4` to dispatch by content type.\n",
    ]
    (DOCS / "SYSTEM_MAP.md").write_text("".join(out))
    print("SYSTEM_MAP.md written")


# ---------- DEPENDENCY_MAP.md ----------
def write_dependency_map():
    """Compute per-package who-imports-whom inside src/mediahub/."""
    pkg_root = ROOT / "src" / "mediahub"
    dep: dict[str, set[str]] = {}
    for p in pkg_root.rglob("*.py"):
        rel = p.relative_to(pkg_root)
        if not rel.parts:
            continue
        owner = rel.parts[0]
        try:
            text = p.read_text()
        except Exception:
            continue
        for m in re.finditer(r"^\s*(?:from|import)\s+mediahub\.([a-z_]+)", text, re.MULTILINE):
            target = m.group(1)
            if target != owner:
                dep.setdefault(owner, set()).add(target)

    out = [
        "# Dependency Map\n\n",
        "Per-package internal dependencies. `A → B` means files in package `A` ",
        "import from package `B`.\n\n",
        "_Auto-generated by walking `src/mediahub/` and grepping `from mediahub.<pkg>`._\n\n",
    ]
    out.append("| Package | Depends on |\n|---|---|\n")
    for k in sorted(dep):
        deps = sorted(dep[k])
        out.append(f"| `{k}` | {', '.join(f'`{d}`' for d in deps)} |\n")

    # External requirements
    out.append("\n## External Python dependencies\n\n")
    req = ROOT / "requirements.txt"
    if req.exists():
        out.append("```\n")
        out.append(req.read_text())
        out.append("\n```\n")
    (DOCS / "DEPENDENCY_MAP.md").write_text("".join(out))
    print("DEPENDENCY_MAP.md written")


# ---------- FEATURE_INVENTORY.md ----------
def write_features():
    out = [
        "# Feature Inventory\n\n",
        "User-visible features, mapped to the routes / modules that implement them.\n\n",
        "| Feature | Route / Entry | Module |\n|---|---|---|\n",
    ]
    rows = [
        ("Upload meet results", "POST `/upload`", "`mediahub.web.web::upload_post`"),
        (
            "Watch upload progress",
            "GET `/runs/<id>` + `/api/runs/<id>/status`",
            "`mediahub.web.web::run_status`",
        ),
        ("Review generated cards", "GET `/review/<id>`", "`mediahub.web.web::review`"),
        ("Edit a card caption", "POST `/api/runs/<id>/cards/<card_id>`", "`mediahub.web.web`"),
        ("Download pack ZIP", "GET `/api/runs/<id>/export`", "`mediahub.web.web::export_run`"),
        ("Inspect detector trace", "GET `/api/runs/<id>/trust`", "`mediahub.web.web`"),
        ("Privacy: list runs", "GET `/privacy`", "`mediahub.web.web`"),
        ("Privacy: delete run", "POST `/privacy/run/<id>/delete`", "`mediahub.web.web`"),
        ("Privacy: clear PB cache", "POST `/privacy/cache/clear`", "`mediahub.web.web`"),
        ("Ground-truth eval", "GET/POST `/ground-truth/<id>`", "`mediahub.web.ground_truth`"),
        ("Brand kit upload", "POST `/api/brand-kit/upload`", "`mediahub.web.brand_kit_upload`"),
        ("Live AI caption", "POST `/api/ai-caption`", "`mediahub.web.ai_caption`"),
        ("Manage secrets", "GET/POST `/settings/secrets`", "`mediahub.web.secrets_store`"),
        ("Health check", "GET `/healthz`", "`mediahub.web.web`"),
        ("Research roadmap", "GET `/research`", "`mediahub.web.web`"),
        ("Voice list", "GET `/api/voices`", "`mediahub.voice.learned.store`"),
        ("Media library", "GET/POST `/api/media-library`", "`mediahub.media_library.store`"),
        (
            "Cutout providers",
            "config: `MEDIAHUB_CUTOUT_PROVIDER`",
            "`mediahub.media_ai.providers.*`",
        ),
        ("Creative brief vision", "internal", "`mediahub.creative_brief.generator`"),
        ("PB verification", "internal", "`mediahub.pb_discovery.discover`"),
        ("Content pack ZIP", "internal", "`mediahub.content_pack.builder`"),
    ]
    for f, route, mod in rows:
        out.append(f"| {f} | {route} | {mod} |\n")
    (DOCS / "FEATURE_INVENTORY.md").write_text("".join(out))
    print("FEATURE_INVENTORY.md written")


def main():
    DOCS.mkdir(exist_ok=True)
    write_inventory()
    write_routes()
    write_api()
    write_env()
    write_detectors()
    write_prompts()
    write_system_map()
    write_dependency_map()
    write_features()


if __name__ == "__main__":
    main()
