"""Deterministic product mockups (P6.3, Build 2) — Smartmockups-class previews.

Composites a piece of artwork (a rendered card, a generated image, any library
asset) into a clean, branded product scene so a club can preview "what would the
poster / framed print / phone post / merch flatlay look like" before it commits
to print (feeds the P6.19 print/merch previews).

**Deterministic, key-free, in-house.** This is the *deterministic* half of P6.3,
not the AI half: the scenes are drawn from first-party PIL primitives (gradients,
rounded rectangles, soft shadows) — MediaHub's own licence-clean mockup scenes,
never a third-party stock photo. The same artwork + template always produces the
same bytes. No provider, no quota, no provenance stamp (nothing was generated by
a model). It is therefore allowed to be deterministic under the engine rules.

Public API:
    list_templates() -> list[dict]
    compose_mockup(artwork: bytes, template_id: str, *, accent=None) -> bytes
"""

from __future__ import annotations

import io
from dataclasses import dataclass
from typing import Optional

from PIL import Image, ImageDraw, ImageFilter


class MockupError(ValueError):
    """Raised for an unknown template or unreadable artwork."""


@dataclass(frozen=True)
class MockupTemplate:
    id: str
    label: str
    description: str
    width: int
    height: int
    kind: str  # poster | frame | phone | flatlay | tee | mug | tote
    # Artwork target box as fractions of the canvas (x, y, w, h).
    box: tuple[float, float, float, float]


MOCKUP_TEMPLATES: dict[str, MockupTemplate] = {
    "poster_wall": MockupTemplate(
        "poster_wall",
        "Poster on a wall",
        "A framed portrait poster on a softly-lit, brand-tinted wall.",
        1080,
        1350,
        "poster",
        (0.20, 0.12, 0.60, 0.74),
    ),
    "framed_print": MockupTemplate(
        "framed_print",
        "Framed print",
        "A matted, framed square print on a neutral wall.",
        1080,
        1080,
        "frame",
        (0.18, 0.14, 0.64, 0.66),
    ),
    "phone_post": MockupTemplate(
        "phone_post",
        "Phone post",
        "The artwork on a phone screen — how a story/feed post reads on device.",
        1080,
        1350,
        "phone",
        (0.28, 0.12, 0.44, 0.74),
    ),
    "flatlay": MockupTemplate(
        "flatlay",
        "Card flatlay",
        "The card resting on a surface with a soft shadow — a tactile preview.",
        1080,
        1080,
        "flatlay",
        (0.16, 0.16, 0.68, 0.68),
    ),
    # --- Merch product scenes (roadmap 1.20 print/merch previews) ----------
    "tee": MockupTemplate(
        "tee",
        "T-shirt",
        "The design on a club t-shirt — how the merch reads on apparel.",
        1080,
        1080,
        "tee",
        (0.36, 0.34, 0.28, 0.30),
    ),
    "mug": MockupTemplate(
        "mug",
        "Mug",
        "The artwork wrapped on a ceramic mug — a fundraising-stall preview.",
        1080,
        1080,
        "mug",
        (0.27, 0.37, 0.37, 0.30),
    ),
    "tote": MockupTemplate(
        "tote",
        "Tote bag",
        "The design printed on a cotton tote — the single-print accessory preview.",
        1080,
        1080,
        "tote",
        (0.30, 0.33, 0.40, 0.44),
    ),
}


def list_templates() -> list[dict]:
    return [
        {
            "id": t.id,
            "label": t.label,
            "description": t.description,
            "aspect": f"{t.width}x{t.height}",
        }
        for t in MOCKUP_TEMPLATES.values()
    ]


# ---------------------------------------------------------------------------
# Colour helpers
# ---------------------------------------------------------------------------


def _hex_to_rgb(value: Optional[str], default: tuple[int, int, int]) -> tuple[int, int, int]:
    if not value:
        return default
    s = value.strip().lstrip("#")
    if len(s) == 3:
        s = "".join(c * 2 for c in s)
    if len(s) != 6:
        return default
    try:
        return (int(s[0:2], 16), int(s[2:4], 16), int(s[4:6], 16))
    except ValueError:
        return default


def _mix(a: tuple[int, int, int], b: tuple[int, int, int], t: float) -> tuple[int, int, int]:
    return tuple(int(round(a[i] + (b[i] - a[i]) * t)) for i in range(3))  # type: ignore[return-value]


def _vertical_gradient(
    w: int, h: int, top: tuple[int, int, int], bottom: tuple[int, int, int]
) -> Image.Image:
    base = Image.new("RGB", (w, h), top)
    draw = ImageDraw.Draw(base)
    for y in range(h):
        draw.line([(0, y), (w, y)], fill=_mix(top, bottom, y / max(1, h - 1)))
    return base


# ---------------------------------------------------------------------------
# Compositing helpers
# ---------------------------------------------------------------------------


def _fit_contain(art: Image.Image, w: int, h: int) -> Image.Image:
    """Resize art to fit within (w, h) preserving aspect, on a transparent tile."""
    w = max(1, w)
    h = max(1, h)
    scale = min(w / art.width, h / art.height)
    nw, nh = max(1, int(art.width * scale)), max(1, int(art.height * scale))
    resized = art.resize((nw, nh), Image.LANCZOS)
    tile = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    tile.paste(resized, ((w - nw) // 2, (h - nh) // 2), resized)
    return tile


def _soft_shadow(
    canvas: Image.Image,
    box: tuple[int, int, int, int],
    *,
    blur: int = 26,
    alpha: int = 110,
    radius: int = 8,
    dy: int = 14,
) -> None:
    x, y, w, h = box
    shadow = Image.new("RGBA", canvas.size, (0, 0, 0, 0))
    sd = ImageDraw.Draw(shadow)
    sd.rounded_rectangle([x, y + dy, x + w, y + h + dy], radius=radius, fill=(0, 0, 0, alpha))
    shadow = shadow.filter(ImageFilter.GaussianBlur(blur))
    canvas.alpha_composite(shadow)


def _frac_box(tpl: MockupTemplate) -> tuple[int, int, int, int]:
    fx, fy, fw, fh = tpl.box
    return (int(fx * tpl.width), int(fy * tpl.height), int(fw * tpl.width), int(fh * tpl.height))


def _backdrop(tpl: MockupTemplate, accent: Optional[str]) -> Image.Image:
    ac = _hex_to_rgb(accent, (90, 100, 120))
    if tpl.kind in ("poster", "phone"):
        top = _mix((245, 246, 248), ac, 0.10)
        bottom = _mix((210, 214, 220), ac, 0.22)
    elif tpl.kind == "frame":
        top, bottom = (238, 238, 240), (222, 222, 226)
    elif tpl.kind in ("tee", "mug", "tote"):  # neutral studio backdrop for merch
        top = _mix((242, 241, 238), ac, 0.05)
        bottom = _mix((221, 220, 216), ac, 0.10)
    else:  # flatlay
        top = _mix((236, 234, 230), ac, 0.06)
        bottom = _mix((216, 213, 208), ac, 0.12)
    return _vertical_gradient(tpl.width, tpl.height, top, bottom).convert("RGBA")


# ---------------------------------------------------------------------------
# Per-kind placement
# ---------------------------------------------------------------------------


def _place_poster(canvas: Image.Image, art: Image.Image, box, accent) -> None:
    x, y, w, h = box
    _soft_shadow(canvas, (x, y, w, h), blur=30, alpha=120, radius=2, dy=18)
    frame = _hex_to_rgb(accent, (28, 30, 36))
    fr = ImageDraw.Draw(canvas)
    pad = max(8, int(w * 0.03))
    fr.rectangle([x - pad, y - pad, x + w + pad, y + h + pad], fill=frame)
    tile = _fit_contain(art, w, h)
    canvas.paste(tile, (x, y), tile)


def _place_frame(canvas: Image.Image, art: Image.Image, box, accent) -> None:
    x, y, w, h = box
    _soft_shadow(canvas, (x, y, w, h), blur=24, alpha=100, radius=2, dy=14)
    dr = ImageDraw.Draw(canvas)
    frame = (32, 32, 36)
    mat = (250, 250, 248)
    fpad = max(10, int(w * 0.04))
    mpad = max(18, int(w * 0.08))
    dr.rectangle([x - fpad, y - fpad, x + w + fpad, y + h + fpad], fill=frame)
    dr.rectangle([x, y, x + w, y + h], fill=mat)
    inner = (x + mpad, y + mpad, w - 2 * mpad, h - 2 * mpad)
    tile = _fit_contain(art, inner[2], inner[3])
    canvas.paste(tile, (inner[0], inner[1]), tile)


def _place_phone(canvas: Image.Image, art: Image.Image, box, accent) -> None:
    x, y, w, h = box
    _soft_shadow(canvas, (x, y, w, h), blur=30, alpha=120, radius=44, dy=18)
    dr = ImageDraw.Draw(canvas)
    body = max(10, int(w * 0.05))
    dr.rounded_rectangle(
        [x - body, y - body, x + w + body, y + h + body], radius=int(w * 0.14), fill=(18, 18, 22)
    )
    # Screen — cover-fit so the post fills the device.
    screen = Image.new("RGBA", (w, h), (0, 0, 0, 255))
    scale = max(w / art.width, h / art.height)
    nw, nh = int(art.width * scale), int(art.height * scale)
    resized = art.resize((max(1, nw), max(1, nh)), Image.LANCZOS)
    screen.paste(resized, ((w - nw) // 2, (h - nh) // 2))
    rounded = Image.new("L", (w, h), 0)
    ImageDraw.Draw(rounded).rounded_rectangle([0, 0, w, h], radius=int(w * 0.10), fill=255)
    canvas.paste(screen, (x, y), rounded)


def _place_flatlay(canvas: Image.Image, art: Image.Image, box, accent) -> None:
    x, y, w, h = box
    tile = _fit_contain(art, w, h)
    # A gentle, fixed rotation for a tactile "placed on a desk" feel (deterministic).
    rotated = tile.rotate(-4, expand=True, resample=Image.BICUBIC)
    rx = x + (w - rotated.width) // 2
    ry = y + (h - rotated.height) // 2
    _soft_shadow(
        canvas, (rx, ry, rotated.width, rotated.height), blur=22, alpha=95, radius=10, dy=12
    )
    canvas.alpha_composite(rotated, (rx, ry))


def _garment_tone(accent: Optional[str]) -> tuple[int, int, int]:
    """A brand-tinted heather tone for the garment/product body (deterministic)."""
    return _mix((66, 70, 78), _hex_to_rgb(accent, (66, 70, 78)), 0.20)


def _place_tee(canvas: Image.Image, art: Image.Image, box, accent) -> None:
    """A simple t-shirt silhouette with the artwork on the chest."""
    w, h = canvas.size
    dr = ImageDraw.Draw(canvas)
    garment = _garment_tone(accent)
    cx = w // 2
    bw, bh = int(w * 0.46), int(h * 0.54)
    bx, by = cx - bw // 2, int(h * 0.27)
    # sleeves (drawn first so the body overlaps them)
    sl = int(w * 0.14)
    dr.polygon(
        [(bx, by), (bx - sl, by + int(bh * 0.22)), (bx + int(bw * 0.10), by + int(bh * 0.30))],
        fill=garment,
    )
    dr.polygon(
        [
            (bx + bw, by),
            (bx + bw + sl, by + int(bh * 0.22)),
            (bx + bw - int(bw * 0.10), by + int(bh * 0.30)),
        ],
        fill=garment,
    )
    dr.rounded_rectangle([bx, by, bx + bw, by + bh], radius=int(bw * 0.07), fill=garment)
    # collar — a darker rib with a backdrop-toned neckline notch
    rib = _mix(garment, (0, 0, 0), 0.18)
    neck = canvas.getpixel((6, 6))[:3]
    dr.ellipse(
        [cx - int(w * 0.085), by - int(h * 0.012), cx + int(w * 0.085), by + int(h * 0.052)],
        fill=rib,
    )
    dr.ellipse(
        [cx - int(w * 0.066), by - int(h * 0.03), cx + int(w * 0.066), by + int(h * 0.03)],
        fill=neck,
    )
    x, y, bw2, bh2 = box
    tile = _fit_contain(art, bw2, bh2)
    _soft_shadow(canvas, (x, y, tile.width, tile.height), blur=10, alpha=55, radius=6, dy=6)
    canvas.alpha_composite(tile, (x + (bw2 - tile.width) // 2, y + (bh2 - tile.height) // 2))


def _place_mug(canvas: Image.Image, art: Image.Image, box, accent) -> None:
    """A ceramic mug with a handle and the artwork wrapped on the front."""
    w, h = canvas.size
    dr = ImageDraw.Draw(canvas)
    body = _garment_tone(accent)
    bx, by = int(w * 0.24), int(h * 0.30)
    bw, bh = int(w * 0.44), int(h * 0.42)
    # handle (ring) on the right
    hx = bx + bw - int(bw * 0.04)
    dr.ellipse(
        [hx, by + int(bh * 0.18), hx + int(bw * 0.34), by + int(bh * 0.74)],
        outline=body,
        width=int(bw * 0.10),
    )
    dr.rounded_rectangle([bx, by, bx + bw, by + bh], radius=int(bw * 0.12), fill=body)
    # subtle rim highlight
    dr.ellipse(
        [bx + int(bw * 0.06), by - int(bh * 0.03), bx + bw - int(bw * 0.06), by + int(bh * 0.07)],
        fill=_mix(body, (255, 255, 255), 0.18),
    )
    x, y, bw2, bh2 = box
    tile = _fit_contain(art, bw2, bh2)
    canvas.alpha_composite(tile, (x + (bw2 - tile.width) // 2, y + (bh2 - tile.height) // 2))


def _place_tote(canvas: Image.Image, art: Image.Image, box, accent) -> None:
    """A cotton tote bag with two handles and a single front print."""
    w, h = canvas.size
    dr = ImageDraw.Draw(canvas)
    fabric = _mix((226, 222, 212), _hex_to_rgb(accent, (226, 222, 212)), 0.10)
    bx, by = int(w * 0.26), int(h * 0.30)
    bw, bh = int(w * 0.48), int(h * 0.50)
    # handles (two arcs rising from the top edge)
    hw = int(bw * 0.10)
    dr.arc(
        [bx + int(bw * 0.10), by - int(bh * 0.30), bx + int(bw * 0.42), by + int(bh * 0.10)],
        180,
        360,
        fill=fabric,
        width=hw,
    )
    dr.arc(
        [bx + int(bw * 0.58), by - int(bh * 0.30), bx + int(bw * 0.90), by + int(bh * 0.10)],
        180,
        360,
        fill=fabric,
        width=hw,
    )
    _soft_shadow(canvas, (bx, by, bw, bh), blur=24, alpha=70, radius=10, dy=14)
    dr.rounded_rectangle([bx, by, bx + bw, by + bh], radius=int(bw * 0.04), fill=fabric)
    x, y, bw2, bh2 = box
    tile = _fit_contain(art, bw2, bh2)
    canvas.alpha_composite(tile, (x + (bw2 - tile.width) // 2, y + (bh2 - tile.height) // 2))


_PLACERS = {
    "poster": _place_poster,
    "frame": _place_frame,
    "phone": _place_phone,
    "flatlay": _place_flatlay,
    "tee": _place_tee,
    "mug": _place_mug,
    "tote": _place_tote,
}


def compose_mockup(artwork: bytes, template_id: str, *, accent: Optional[str] = None) -> bytes:
    """Composite ``artwork`` into the named product scene; return PNG bytes."""
    tpl = MOCKUP_TEMPLATES.get(template_id)
    if tpl is None:
        raise MockupError(f"Unknown mockup template: {template_id!r}")
    try:
        art = Image.open(io.BytesIO(artwork)).convert("RGBA")
    except Exception as e:
        raise MockupError(f"Could not read the artwork image: {e}")
    canvas = _backdrop(tpl, accent)
    _PLACERS[tpl.kind](canvas, art, _frac_box(tpl), accent)
    out = io.BytesIO()
    canvas.convert("RGB").save(out, format="PNG")
    return out.getvalue()


__all__ = ["MockupError", "MockupTemplate", "MOCKUP_TEMPLATES", "list_templates", "compose_mockup"]
