"""Deterministic product mockups (P6.3, Build 2) — Smartmockups-class previews.

Composites a piece of artwork (a rendered card, a generated image, any library
asset) into a clean, branded product scene so a club can preview "what would the
poster / framed print / phone post / merch flatlay look like" before it commits
to print (feeds the P6.19 print/merch previews).

**Deterministic, key-free, in-house.** This is the *deterministic* half of P6.3,
not the AI half: the scenes are drawn from first-party PIL primitives (gradients,
rounded rectangles, soft shadows) — MediaHub's own licence-clean mockup scenes,
never a third-party stock photo. The same artwork + template always produces the
same bytes. No provider, no quota, no provenance stamp (nothing was generated by
a model). It is therefore allowed to be deterministic under the engine rules.

Public API:
    list_templates() -> list[dict]
    compose_mockup(artwork: bytes, template_id: str, *, accent=None) -> bytes
"""

from __future__ import annotations

import io
from dataclasses import dataclass
from typing import Optional

from PIL import Image, ImageDraw, ImageFilter


class MockupError(ValueError):
    """Raised for an unknown template or unreadable artwork."""


@dataclass(frozen=True)
class MockupTemplate:
    id: str
    label: str
    description: str
    width: int
    height: int
    kind: str  # "poster" | "frame" | "phone" | "flatlay"
    # Artwork target box as fractions of the canvas (x, y, w, h).
    box: tuple[float, float, float, float]


MOCKUP_TEMPLATES: dict[str, MockupTemplate] = {
    "poster_wall": MockupTemplate(
        "poster_wall",
        "Poster on a wall",
        "A framed portrait poster on a softly-lit, brand-tinted wall.",
        1080,
        1350,
        "poster",
        (0.20, 0.12, 0.60, 0.74),
    ),
    "framed_print": MockupTemplate(
        "framed_print",
        "Framed print",
        "A matted, framed square print on a neutral wall.",
        1080,
        1080,
        "frame",
        (0.18, 0.14, 0.64, 0.66),
    ),
    "phone_post": MockupTemplate(
        "phone_post",
        "Phone post",
        "The artwork on a phone screen — how a story/feed post reads on device.",
        1080,
        1350,
        "phone",
        (0.28, 0.12, 0.44, 0.74),
    ),
    "flatlay": MockupTemplate(
        "flatlay",
        "Card flatlay",
        "The card resting on a surface with a soft shadow — a tactile preview.",
        1080,
        1080,
        "flatlay",
        (0.16, 0.16, 0.68, 0.68),
    ),
}


def list_templates() -> list[dict]:
    return [
        {
            "id": t.id,
            "label": t.label,
            "description": t.description,
            "aspect": f"{t.width}x{t.height}",
        }
        for t in MOCKUP_TEMPLATES.values()
    ]


# ---------------------------------------------------------------------------
# Colour helpers
# ---------------------------------------------------------------------------


def _hex_to_rgb(value: Optional[str], default: tuple[int, int, int]) -> tuple[int, int, int]:
    if not value:
        return default
    s = value.strip().lstrip("#")
    if len(s) == 3:
        s = "".join(c * 2 for c in s)
    if len(s) != 6:
        return default
    try:
        return (int(s[0:2], 16), int(s[2:4], 16), int(s[4:6], 16))
    except ValueError:
        return default


def _mix(a: tuple[int, int, int], b: tuple[int, int, int], t: float) -> tuple[int, int, int]:
    return tuple(int(round(a[i] + (b[i] - a[i]) * t)) for i in range(3))  # type: ignore[return-value]


def _vertical_gradient(
    w: int, h: int, top: tuple[int, int, int], bottom: tuple[int, int, int]
) -> Image.Image:
    base = Image.new("RGB", (w, h), top)
    draw = ImageDraw.Draw(base)
    for y in range(h):
        draw.line([(0, y), (w, y)], fill=_mix(top, bottom, y / max(1, h - 1)))
    return base


# ---------------------------------------------------------------------------
# Compositing helpers
# ---------------------------------------------------------------------------


def _fit_contain(art: Image.Image, w: int, h: int) -> Image.Image:
    """Resize art to fit within (w, h) preserving aspect, on a transparent tile."""
    w = max(1, w)
    h = max(1, h)
    scale = min(w / art.width, h / art.height)
    nw, nh = max(1, int(art.width * scale)), max(1, int(art.height * scale))
    resized = art.resize((nw, nh), Image.LANCZOS)
    tile = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    tile.paste(resized, ((w - nw) // 2, (h - nh) // 2), resized)
    return tile


def _soft_shadow(
    canvas: Image.Image,
    box: tuple[int, int, int, int],
    *,
    blur: int = 26,
    alpha: int = 110,
    radius: int = 8,
    dy: int = 14,
) -> None:
    x, y, w, h = box
    shadow = Image.new("RGBA", canvas.size, (0, 0, 0, 0))
    sd = ImageDraw.Draw(shadow)
    sd.rounded_rectangle([x, y + dy, x + w, y + h + dy], radius=radius, fill=(0, 0, 0, alpha))
    shadow = shadow.filter(ImageFilter.GaussianBlur(blur))
    canvas.alpha_composite(shadow)


def _frac_box(tpl: MockupTemplate) -> tuple[int, int, int, int]:
    fx, fy, fw, fh = tpl.box
    return (int(fx * tpl.width), int(fy * tpl.height), int(fw * tpl.width), int(fh * tpl.height))


def _backdrop(tpl: MockupTemplate, accent: Optional[str]) -> Image.Image:
    ac = _hex_to_rgb(accent, (90, 100, 120))
    if tpl.kind in ("poster", "phone"):
        top = _mix((245, 246, 248), ac, 0.10)
        bottom = _mix((210, 214, 220), ac, 0.22)
    elif tpl.kind == "frame":
        top, bottom = (238, 238, 240), (222, 222, 226)
    else:  # flatlay
        top = _mix((236, 234, 230), ac, 0.06)
        bottom = _mix((216, 213, 208), ac, 0.12)
    return _vertical_gradient(tpl.width, tpl.height, top, bottom).convert("RGBA")


# ---------------------------------------------------------------------------
# Per-kind placement
# ---------------------------------------------------------------------------


def _place_poster(canvas: Image.Image, art: Image.Image, box, accent) -> None:
    x, y, w, h = box
    _soft_shadow(canvas, (x, y, w, h), blur=30, alpha=120, radius=2, dy=18)
    frame = _hex_to_rgb(accent, (28, 30, 36))
    fr = ImageDraw.Draw(canvas)
    pad = max(8, int(w * 0.03))
    fr.rectangle([x - pad, y - pad, x + w + pad, y + h + pad], fill=frame)
    canvas.paste(_fit_contain(art, w, h), (x, y), _fit_contain(art, w, h))


def _place_frame(canvas: Image.Image, art: Image.Image, box, accent) -> None:
    x, y, w, h = box
    _soft_shadow(canvas, (x, y, w, h), blur=24, alpha=100, radius=2, dy=14)
    dr = ImageDraw.Draw(canvas)
    frame = (32, 32, 36)
    mat = (250, 250, 248)
    fpad = max(10, int(w * 0.04))
    mpad = max(18, int(w * 0.08))
    dr.rectangle([x - fpad, y - fpad, x + w + fpad, y + h + fpad], fill=frame)
    dr.rectangle([x, y, x + w, y + h], fill=mat)
    inner = (x + mpad, y + mpad, w - 2 * mpad, h - 2 * mpad)
    tile = _fit_contain(art, inner[2], inner[3])
    canvas.paste(tile, (inner[0], inner[1]), tile)


def _place_phone(canvas: Image.Image, art: Image.Image, box, accent) -> None:
    x, y, w, h = box
    _soft_shadow(canvas, (x, y, w, h), blur=30, alpha=120, radius=44, dy=18)
    dr = ImageDraw.Draw(canvas)
    body = max(10, int(w * 0.05))
    dr.rounded_rectangle(
        [x - body, y - body, x + w + body, y + h + body], radius=int(w * 0.14), fill=(18, 18, 22)
    )
    # Screen — cover-fit so the post fills the device.
    screen = Image.new("RGBA", (w, h), (0, 0, 0, 255))
    scale = max(w / art.width, h / art.height)
    nw, nh = int(art.width * scale), int(art.height * scale)
    resized = art.resize((max(1, nw), max(1, nh)), Image.LANCZOS)
    screen.paste(resized, ((w - nw) // 2, (h - nh) // 2))
    rounded = Image.new("L", (w, h), 0)
    ImageDraw.Draw(rounded).rounded_rectangle([0, 0, w, h], radius=int(w * 0.10), fill=255)
    canvas.paste(screen, (x, y), rounded)


def _place_flatlay(canvas: Image.Image, art: Image.Image, box, accent) -> None:
    x, y, w, h = box
    tile = _fit_contain(art, w, h)
    # A gentle, fixed rotation for a tactile "placed on a desk" feel (deterministic).
    rotated = tile.rotate(-4, expand=True, resample=Image.BICUBIC)
    rx = x + (w - rotated.width) // 2
    ry = y + (h - rotated.height) // 2
    _soft_shadow(
        canvas, (rx, ry, rotated.width, rotated.height), blur=22, alpha=95, radius=10, dy=12
    )
    canvas.alpha_composite(rotated, (rx, ry))


_PLACERS = {
    "poster": _place_poster,
    "frame": _place_frame,
    "phone": _place_phone,
    "flatlay": _place_flatlay,
}


def compose_mockup(artwork: bytes, template_id: str, *, accent: Optional[str] = None) -> bytes:
    """Composite ``artwork`` into the named product scene; return PNG bytes."""
    tpl = MOCKUP_TEMPLATES.get(template_id)
    if tpl is None:
        raise MockupError(f"Unknown mockup template: {template_id!r}")
    try:
        art = Image.open(io.BytesIO(artwork)).convert("RGBA")
    except Exception as e:
        raise MockupError(f"Could not read the artwork image: {e}")
    canvas = _backdrop(tpl, accent)
    _PLACERS[tpl.kind](canvas, art, _frac_box(tpl), accent)
    out = io.BytesIO()
    canvas.convert("RGB").save(out, format="PNG")
    return out.getvalue()


__all__ = ["MockupError", "MockupTemplate", "MOCKUP_TEMPLATES", "list_templates", "compose_mockup"]
